/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_warp_picalculator_TestJNI */

#ifndef _Included_org_warp_picalculator_TestJNI
#define _Included_org_warp_picalculator_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_warp_picalculator_TestJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_warp_picalculator_TestJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
