package org.warpgate.pi.calculator;

public enum Errori {
	ERROR,
	DIVISION_BY_ZERO,
	UNBALANCED_BRACKETS,
	NOT_IMPLEMENTED,
	NEGATIVE_PARAMETER,
	NUMBER_TOO_LARGE,
	NUMBER_TOO_SMALL,
	CONVERSION_ERROR,
	SYNTAX_ERROR
}
